name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0
  
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 5.8.4
  intl: ^0.18.1
  intl_utils: 2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/strings/generated
  arb_dir: lib/src/strings/l10n
